In [ ]:
import numpy as np

In [ ]:
import pandas as pd

# **CREATING SERIES FROM LIST**

In [ ]:
a=[1,2,3,4]
df=pd.Series(a)
df

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
print(df)

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
print(type(df))

<class 'pandas.core.series.Series'>

# **CREATING SERIES FROM NUMPY ARRAY**

In [ ]:
b=np.arange(68,78)
b

array([68, 69, 70, 71, 72, 73, 74, 75, 76, 77])

In [ ]:
print(type(b))

<class 'numpy.ndarray'>

In [ ]:
df1=pd.Series(b)
df1

0    68
1    69
2    70
3    71
4    72
5    73
6    74
7    75
8    76
9    77
dtype: int64

# **CREATING SERIES FROM DICTIONARY**

In [ ]:
d={"a":[1,2,3],"b":[4,5,6]}
d

{'a': [1, 2, 3], 'b': [4, 5, 6]}

In [ ]:
type(d)

dict

In [ ]:
df2=pd.Series(d)
df2

a    [1, 2, 3]
b    [4, 5, 6]
dtype: object

In [ ]:
print(type(df2))

<class 'pandas.core.series.Series'>

In [ ]:
d1={"hi":[99,90],"hlo":[839,10]}
d1

{'hi': [99, 90], 'hlo': [839, 10]}

In [ ]:
pd.Series(d1)

hi      [99, 90]
hlo    [839, 10]
dtype: object

In [ ]:
arr_0=np.arange(10)
arr_0

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
pd.Series(arr_0,index=range(90,100))

90    0
91    1
92    2
93    3
94    4
95    5
96    6
97    7
98    8
99    9
dtype: int64

In [ ]:
pd.Series()

Series([], dtype: object)

In [ ]:
arr_1=np.array({1,2,3})
print(arr_1)
type(arr_1)

{1, 2, 3}

numpy.ndarray

# **changing the name of index number**

In [ ]:
import pandas as pd

In [ ]:
l=[10,30,888]
pd.Series(l,index=["a","bc","d"])

a      10
bc     30
d     888
dtype: int64

In [ ]:
pd.Series(l,index=[[7,8],90,88])

[7, 8]     10
90         30
88        888
dtype: int64

In [ ]:
pd.Series(l,index=(89,29,90))

89     10
29     30
90    888
dtype: int64

# **pandas DataFrame**
-  we can not  creat dataframe from 1d array
- we can create the dataframe from 2d array

In [ ]:
d2={"a":1,"b":2}
print(d2)
print(type(d2))

{'a': 1, 'b': 2}
<class 'dict'>

In [ ]:
df3=pd.DataFrame(d2)

ValueError: If using all scalar values, you must pass an index

In [ ]:
df3=pd.DataFrame(d2,index= [0])
df3

   a  b
0  1  2

In [ ]:
d={"col":[1,2],"col2":[3,4]}
print(d)
print(type(d))

{'col': [1, 2], 'col2': [3, 4]}
<class 'dict'>

In [ ]:
pd.Series(d)

col     [1, 2]
col2    [3, 4]
dtype: object

In [ ]:
df4=pd.DataFrame(d)
df4

   col  col2
0    1     3
1    2     4

In [ ]:
 print(type(df4))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
df4.shape

(2, 2)

# **CREATING DATAFRAME FROM NESTED LIST**
- the list which can be converted into 2d array that list will be converted to dataframe

In [ ]:
l1=[[1,2,3],[4,5,6],[7,8,9]]
print(l1)
print(type(l1))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>

In [ ]:
import numpy as np

In [ ]:
arr_1=np.array(l1)
print(type(arr_1))
print(arr_1)

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]

In [ ]:
df5=pd.DataFrame(l1)
print(type(df5))
print(df5)

<class 'pandas.core.frame.DataFrame'>
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
df5

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
arr_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
pd.Series(arr_1)

ValueError: Data must be 1-dimensional, got ndarray of shape (3, 3) instead

In [ ]:
l1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
df6=pd.DataFrame(l1, index=["a","b","c"] ,columns=["aa","bb","cc"])
df6

   aa  bb  cc
a   1   2   3
b   4   5   6
c   7   8   9

In [ ]:
d=np.array([[1,2,3,4],[5,6,7,8]])
df7=pd.DataFrame(d).T
df7

   0  1
0  1  5
1  2  6
2  3  7
3  4  8

In [ ]:
df7.ndim

2

In [ ]:
type(df7)

pandas.core.frame.DataFrame

 # **pandas**

In [ ]:
d={"age":[22,30,80,40,58],"Salary":[7000,3729,9028,73748,38838],"Gender":["M","F","F","M","F"]}
d

{'age': [22, 30, 80, 40, 58],
 'Salary': [7000, 3729, 9028, 73748, 38838],
 'Gender': ['M', 'F', 'F', 'M', 'F']}

In [ ]:
pd.Series(d)

age                   [22, 30, 80, 40, 58]
Salary    [7000, 3729, 9028, 73748, 38838]
Gender                     [M, F, F, M, F]
dtype: object

In [ ]:
df8=pd.DataFrame(d)
df8

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

# **set Index**

In [ ]:
df8["sno"]= np.arange(44,49)
df8

   age  Salary Gender  sno
0   22    7000      M   44
1   30    3729      F   45
2   80    9028      F   46
3   40   73748      M   47
4   58   38838      F   48

In [ ]:
pd.DataFrame(d,set_index=np.arange(44,49))

TypeError: DataFrame.__init__() got an unexpected keyword argument 'set_index'

In [ ]:
df8

   age  Salary Gender  sno
0   22    7000      M   44
1   30    3729      F   45
2   80    9028      F   46
3   40   73748      M   47
4   58   38838      F   48

In [ ]:
df8.set_index("age", inplace=True)

In [ ]:
df8

     Salary Gender  sno
age
22     7000      M   44
30     3729      F   45
80     9028      F   46
40    73748      M   47
58    38838      F   48

In [ ]:
df8.set_index("sno")

     Salary Gender
sno
44     7000      M
45     3729      F
46     9028      F
47    73748      M
48    38838      F

In [ ]:
df8.set_index("sno", inplace=True)

TypeError: 'str' object is not callable

In [ ]:
df9=df8.set_index("Gender")
df9

        Salary  sno
Gender
M         7000   44
F         3729   45
F         9028   46
M        73748   47
F        38838   48

- getting data by index name

In [ ]:
df9.loc["M"]

        Salary  sno
Gender
M         7000   44
M        73748   47

In [ ]:
df10=pd.DataFrame(d)
df10

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

In [ ]:
df10["sno"]=range(44,49)
df10

   age  Salary Gender  sno
0   22    7000      M   44
1   30    3729      F   45
2   80    9028      F   46
3   40   73748      M   47
4   58   38838      F   48

In [ ]:
df11=df10.set_index("sno")
df11

     age  Salary Gender
sno
44    22    7000      M
45    30    3729      F
46    80    9028      F
47    40   73748      M
48    58   38838      F

In [ ]:
df11.loc[47]

age          40
Salary    73748
Gender        M
Name: 47, dtype: object

- to drop paricular index name

In [ ]:
df11.drop(index=47)

     age  Salary Gender
sno
44    22    7000      M
45    30    3729      F
46    80    9028      F
48    58   38838      F

In [ ]:
df11.drop(index=44)

     age  Salary Gender
sno
45    30    3729      F
46    80    9028      F
47    40   73748      M
48    58   38838      F

# **selecting /extracting the requred data**

> Add blockquote

In [3]:
d={"age":[22,30,80,40,58],"Salary":[7000,3729,9028,73748,38838],"Gender":["M","F","F","M","F"]}
d

{'age': [22, 30, 80, 40, 58],
 'Salary': [7000, 3729, 9028, 73748, 38838],
 'Gender': ['M', 'F', 'F', 'M', 'F']}

In [4]:
import pandas as pd

In [5]:
df0=pd.DataFrame(d)
df0

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

In [6]:
df0.loc[:,"age"]

0    22
1    30
2    80
3    40
4    58
Name: age, dtype: int64

In [7]:
df0.loc[:,"age"]

0    22
1    30
2    80
3    40
4    58
Name: age, dtype: int64

In [8]:
df0.loc[:,:]

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

In [10]:
df0.loc[:, "age":"Salary"]

   age  Salary
0   22    7000
1   30    3729
2   80    9028
3   40   73748
4   58   38838

In [11]:
df0.set_index("age")

     Salary Gender
age
22     7000      M
30     3729      F
80     9028      F
40    73748      M
58    38838      F

In [12]:
df0

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

In [13]:
df0.loc[0:3,:]

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M

- loc work on index name
- iloc work on index number

In [14]:
df0.loc[4]

age          58
Salary    38838
Gender        F
Name: 4, dtype: object

In [15]:
df0.loc[3:4,"age"]

3    40
4    58
Name: age, dtype: int64

In [17]:
# slicing with step
df0.loc[0:5:2]

   age  Salary Gender
0   22    7000      M
2   80    9028      F
4   58   38838      F

- extracting random index name

In [19]:
df0.loc[[0,4,3,0]]

   age  Salary Gender
0   22    7000      M
4   58   38838      F
3   40   73748      M
0   22    7000      M

In [21]:
df0.loc[[0,4,3,0],"age"]

0    22
4    58
3    40
0    22
Name: age, dtype: int64

- extarcting single column

In [29]:
df0.loc[:,"age":"Salaray"]

   age  Salary
0   22    7000
1   30    3729
2   80    9028
3   40   73748
4   58   38838

In [28]:
df0

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

- extarct multiple columns based on slicing

In [30]:
df0.loc[:,"age":]

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

- random exxtarcting data

In [32]:
df0.loc[[0,4,2,3],["Salary","age"]]

   Salary  age
0    7000   22
4   38838   58
2    9028   80
3   73748   40

- **extarcting single row**
- df.loc[rowname]

In [33]:
df0

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

In [34]:
df0.loc[0]

age         22
Salary    7000
Gender       M
Name: 0, dtype: object

- **extracting rows by slicing**
- df.loc[start:end]

In [41]:
df0.loc[0:4]

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

- ** extarcting rows by slicing with step**
- df.loc[star:end:step]

In [36]:
df0.loc[0:4:2]

   age  Salary Gender
0   22    7000      M
2   80    9028      F
4   58   38838      F

- **extarcting rows randomly**
- df.loc[[indixname list]]

In [42]:
df0.loc[[0,4,3,1]]

   age  Salary Gender
0   22    7000      M
4   58   38838      F
3   40   73748      M
1   30    3729      F

- **single col**
- df.loc[:,colname]

In [38]:
df0.loc[:,"age"]

0    22
1    30
2    80
3    40
4    58
Name: age, dtype: int64

- **multiple cols by slicing**
- df.loc[:,"start":"end"]

In [40]:
df0.loc[:,"age":"Salary"]

   age  Salary
0   22    7000
1   30    3729
2   80    9028
3   40   73748
4   58   38838

**extarcting random cols**


>  df.loc[  , [list of col]]

In [44]:
df0.loc[ :,["age","Salary","age"]]

   age  Salary  age
0   22    7000   22
1   30    3729   30
2   80    9028   80
3   40   73748   40
4   58   38838   58

**both rows and col are random**
- df.loc[[list of index],[list of cols]]

In [46]:
df0.loc[[0,2,3,0],["age","Salary"]]

   age  Salary
0   22    7000
2   80    9028
3   40   73748
0   22    7000

# **iloc we will to extarct data by index numbers**
- in iloc end will be excluded

In [49]:
import numpy as np

In [57]:
df0

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M
4   58   38838      F

In [60]:
df0.iloc[-2,:]

age          40
Salary    73748
Gender        M
Name: 3, dtype: object

In [48]:
df0.iloc[0:4]

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F
3   40   73748      M

In [61]:
df0.iloc[[-5,-1],:]

   age  Salary Gender
0   22    7000      M
4   58   38838      F

In [62]:
df0.iloc[0:3]

   age  Salary Gender
0   22    7000      M
1   30    3729      F
2   80    9028      F

In [65]:
df0.iloc[:,0:1] # -------> here the last index is not included it will exclude

   age
0   22
1   30
2   80
3   40
4   58

In [67]:
df1=pd.DataFrame(d,index=["a","b","c","d","e"])
df1

   age  Salary Gender
a   22    7000      M
b   30    3729      F
c   80    9028      F
d   40   73748      M
e   58   38838      F

- extarct [a,c,e] and [age ,salaray]

In [69]:
df1.iloc[[0,-3,-1],0:2]

   age  Salary
a   22    7000
c   80    9028
e   58   38838